# Generated by Django 5.2.8 on 2025-11-15 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0005_cultivar'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_kg', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tipo', models.CharField(max_length=20)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='farm.cultivo')),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
