# Generated by Django 5.2.8 on 2025-11-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_fazenda_cidade_fazenda_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='kg_por_saca',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=6),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='sacas_por_ha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='safra',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
