# Generated by Django 5.2.8 on 2025-11-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_cultivo_kg_por_saca_cultivo_sacas_por_ha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultura', models.CharField(max_length=100)),
                ('variedade', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('cultura', 'variedade')},
            },
        ),
    ]
